### ISSUE TITLE
add Binary Ninja

### ISSUE THREAD

**Issue by psifertex** [onethawt/reverseengineering-reading-list#4]
Under Software & Libraries: 

https://binary.ninja/

Happy to submit a PR if you prefer that instead too.

**Comment by onethawt** [comment]
Been traveling for consulting work, will add tomorrow. Thanks!

**Comment by onethawt** [comment]
Added. If you have a more suitable description, let me know.

**Comment by psifertex** [comment]
Looks good, thanks! We do emphasize our API a lot as one of the strengths, but I'm not unhappy with the description there now. :-)
